version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  server:
    build:
      context: server
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    driver: bridge
    name: nfl-rushing-network